-- Oracle version of the main schema
CREATE TABLE students (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(150) NOT NULL,
  grade VARCHAR2(50) NOT NULL,
  school VARCHAR2(150) NOT NULL,
  attendance NUMBER(5,2) DEFAULT 0,
  average NUMBER(5,2) DEFAULT 0,
  status VARCHAR2(30) DEFAULT 'Active'
);

CREATE TABLE activities (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  description VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO students (name, grade, school, attendance, average, status)
VALUES ('Ahmed Alqahtani','10th Grade','Al-Nour High School',96,91.5,'Active');

COMMIT;
